version: "3"

services:
  server:
    build: .
    container_name: app-server
    image: app-server
    ports:
      - '3005:3005'
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true